Repository importPI19fromDHGE/dhge-pi19-sem4, pull requests merged in 2021-06, with the labels that each got.

#67 Mitschriften Systementwurf 31.05.2021
  SWE-KASCHE/README.md
Labels: documentation

#68 Mitschriften System-Entwurf 02.06.2021
  ASM-GUENTHER/README.md
  DBS-DORENDORF/README.md
  EMB-GUENTHER/README.md
  OOP-CASSELT/README.md
  SWE-KASCHE/README.md
  SWS-KUSCHE/README.md
Labels: documentation

#73 ASM (PIB) vom 03.06.21
  ASM-GUENTHER/appendix/praktikum.md
Labels: documentation

#78 Meeting 05.06.2021 SWE LKF
  SWE-KASCHE/README.md
  SWE-KASCHE/appendix/LKF.md
Labels: documentation

#79 Quick JSON-Syntax fix
  SWE-KASCHE/README.md
Labels: documentation

#76 fix image path
  ASM-GUENTHER/appendix/assets/8515_interrupts.jpg
  ASM-GUENTHER/appendix/praktikum.md
Labels: bug, documentation

#83 Basic AVR Cheatsheet
  ASM-GUENTHER/appendix/praktikum-cheatsheet.md
Labels: documentation

#85 Prüfungsaufgaben aus der SWE-Klausur
  SWE-KASCHE/appendix/PRUEFUNGSAUFGABEN.md
Labels: documentation

#86 MPP-Themen-Sammlung von PI18/17/15
  MPP-PI/README.md
Labels: documentation

#88 MPP Themen bearbeiten
  MPP-PI/README.md
Labels: documentation, keep branch

#92 Noch ein paar bearbeitete MPP-Themen
  MPP-PI/README.md
Labels: documentation

#93 Noch ein paar bearbeitete MPP-Themen PART 2
  MPP-PI/README.md
Labels: documentation

#91 MPP Themen Jonathan+Yannis
  MPP-PI/README.md
Labels: documentation

#99 Implement proposed changes to fix #59
  .github/workflows/toc.yml
Labels: bug

#97 MPP Themen
  MPP-PI/README.md
Labels: documentation

#102 Add MPP to pdf workflow
  .github/workflows/pandoc.yml
  MPP-PI/README.md
Labels: enhancement

#105 Mikrocontroller Vortrag hinzufügen
  ASM-GUENTHER/extra/vortraege/mikrocontroller_luis_yannis/mikrocontroller.pdf
Labels: documentation

#108 MPP Teams meeting 21.06.2021
  MPP-PI/README.md
  MPP-PI/assets/v-modell.png
Labels: documentation

#110 add MPP to toc.yml
  .github/workflows/toc.yml
  MPP-PI/README.md
Labels: enhancement

#112 added primitive anki-deck
  MPP-PI/README.md
  MPP-PI/appendix/README.md
  MPP-PI/extra/MPP PI I.apkg
  MPP-PI/extra/README.md
Labels: help wanted

#116 Update README.md
  README.md
Labels: documentation
