Repository importPI19fromDHGE/dhge-pi19-sem4, pull requests merged in 2021-05, with the labels that each got.

#32 DBS: Normalformen
  ABWL-LEDER/README.md
  DBS-DORENDORF/README.md
Labels: documentation

#35 Fix #34
  DBS-DORENDORF/README.md
Labels: oopsie

#36 Fix #34 pt2
  PRO-KASCHE/README.md
Labels: bug

#41 Linting sollte nicht doppelt auf PRs ausgeführt werden
  .github/workflows/lint.yml
Labels: enhancement

#40 Pandoc Action direkt auf PRs ausführen
  .github/workflows/pandoc.yml
Labels: enhancement

#45 Versuch, Linting zu reparieren
  SWE-KASCHE/README.md
Labels: bug

#44 Mitschriften Systementwicklung 12.05.2021
  SWE-KASCHE/README.md
  SWE-KASCHE/assets/konfDiag.jpg
Labels: documentation

#46 Abwl sthinbetween 20211705
  ABWL-LEDER/README.md
Labels: documentation, oopsie

#47 Mitschriften System-Entwicklung 17.05.2021
  SWE-KASCHE/README.md
  SWE-KASCHE/assets/selective_broadcast.jpg
Labels: documentation

#48 ASM Praktikum vom 18.05.21
  .github/workflows/toc.yml
  ASM-GUENTHER/appendix/praktikum.md
Labels: documentation

#49 Mitschriften Systementwicklung 19.05.2021
  SWE-KASCHE/README.md
Labels: documentation

#50 Mitschriften Systementwicklung 25.05.2021
  SWE-KASCHE/README.md
Labels: documentation

#51 Revert "remove RAID presentation from ASM until clearance from DHGE i…
  ASM-GUENTHER/extra/vortraege/raid_max_benedict/RAID_Vortrag_Präsentation.pdf
  ASM-GUENTHER/extra/vortraege/raid_max_benedict/img/Screenshot 2021-03-28_raidkarte_jacob.jpg
  ASM-GUENTHER/extra/vortraege/raid_max_benedict/raid.md
Labels: documentation

#52 ASM vom 26.05.21
  ASM-GUENTHER/appendix/assets/8515_prescaler.jpg
  ASM-GUENTHER/appendix/praktikum.md
Labels: documentation

#54 Frontmatters
  ABWL-LEDER/README.md
  DBS-DORENDORF/README.md
  EMB-GUENTHER/README.md
  OOP-CASSELT/README.md
  PRO-KASCHE/README.md
  SWE-KASCHE/README.md
  SWS-KUSCHE/README.md
Labels: enhancement

#53 ASM vom 28.05.21
  ASM-GUENTHER/appendix/praktikum.md
Labels: documentation
